# Feature engineering
Feature engineering is the process of using domain knowledge to transform raw data into informative features (variables) that enhance machine learning model performance. It involves creating, selecting, and modifying inputs—such as scaling, encoding, or aggregating data—to help algorithms detect patterns more effectively, ultimately increasing predictive accuracy.

In [1]:
# import data and necessary libraries
import pandas as pd

df = pd.read_csv('../data/processed/food_delivery.csv')
df.head()

,order_id,city_tier,customer_age,customer_loyalty_score,order_hour,order_day_of_week,order_month,delivery_distance_km,preparation_time_minutes,delivery_time_minutes,...,cancellation_flag,delayed_delivery_flag,refund_flag,promo_code_used,premium_customer_flag,festival_or_weekend_flag,delivery_partner_experience_years,delivery_efficiency_score,customer_rating_missing,delivery_partner_rating_missing
0,5a87c6ab-e4a8-44ef-8852-f7a63e3b3943,2,21,4.957522,20,6,6,14.117144,23,76,...,False,False,True,False,False,True,9,71.1,0,0
1,8eab78a5-a5c5-41d7-9a5f-5779ee5f2d3d,1,63,38.744721,0,2,2,9.177354,16,34,...,False,False,False,True,False,False,12,100.0,0,0
2,1338cc5b-e5cf-419f-a7c9-4a2577608715,1,68,45.170997,9,2,11,34.753921,41,152,...,False,False,False,False,False,False,10,34.4,0,0
3,5277f2fb-b1b3-4f58-9975-12f8f1b71421,2,30,10.573003,6,6,5,26.596184,9,93,...,False,False,False,False,True,True,1,45.0,0,0
4,df159a97-3a78-4b08-a524-ec433c75b670,2,60,58.284620,12,1,9,26.204152,49,141,...,True,False,False,False,False,False,6,25.1,0,0

In [2]:
# delivery_delay_gap
# delivery_time_minutes – estimated_delivery_time = late, negative = early.

df['delivery_delay_gap'] = df['delivery_time_minutes'] - df['estimated_delivery_time']

In [3]:
# is peak hour
# Binary: 1 if order_hour in {12, 13, 14, 20, 21, 22, 23, 0}. Lunch and dinner rush
df['is_peak_hour'] = df['order_hour'].isin([12, 13, 14, 20, 21, 22, 23, 0])

In [4]:
# cost per km
df['cost_per_km'] = df['delivery_fee'] / df['delivery_distance_km']

In [5]:
# revenue per item
df['revenue_per_item'] = df['order_value'] / df['number_of_items']

In [6]:
# is night order
# Binary: 1 if order_hour in {0, 1, 2, 3, 4, 5}. Late night orders
df['is_night_order'] = df['order_hour'].isin([22 ,23 ,0, 1, 2, 3, 4, 5])

In [7]:
# Display all columns
pd.set_option('display.max_columns', None)

# Optional: widen display
pd.set_option('display.width', 1000)

df.head()

                               order_id  city_tier  customer_age  customer_loyalty_score  order_hour  order_day_of_week  order_month  delivery_distance_km  preparation_time_minutes  delivery_time_minutes  estimated_delivery_time  traffic_level_score  weather_severity_score  restaurant_rating  delivery_partner_rating  customer_rating  order_value  delivery_fee  discount_amount  tip_amount  final_amount_paid  number_of_items  cancellation_flag  delayed_delivery_flag  refund_flag  promo_code_used  premium_customer_flag  festival_or_weekend_flag  delivery_partner_experience_years  delivery_efficiency_score  customer_rating_missing  delivery_partner_rating_missing  delivery_delay_gap  is_peak_hour  cost_per_km  revenue_per_item  is_night_order
0  5a87c6ab-e4a8-44ef-8852-f7a63e3b3943          2            21                4.957522          20                  6            6             14.117144                        23                     76                       68                  5.4                     2.6                4.3                      4.1              2.9   100.000000     14.592602        22.969359   19.940541         111.563784                4              False                  False         True            False                  False                      True                                  9                       71.1                        0                                0                   8          True     1.033680         25.000000           False
1  8eab78a5-a5c5-41d7-9a5f-5779ee5f2d3d          1            63               38.744721           0                  2            2              9.177354                        16                     34                       40                  1.0                     1.6                4.0                      4.2              3.4   100.000000      4.391720         4.434405   16.101949         116.059264                7              False                  False        False             True                  False                     False                                 12                      100.0                        0                                0                  -6          True     0.478539         14.285714            True
2  1338cc5b-e5cf-419f-a7c9-4a2577608715          1            68               45.170997           9                  2           11             34.753921                        41                    152                      142                  8.3                     4.1                4.4                      4.2              3.7   100.000000      9.006407        14.979691   17.681454         111.708170               12              False                  False        False            False                  False                     False                                 10                       34.4                        0                                0                  10         False     0.259148          8.333333           False
3  5277f2fb-b1b3-4f58-9975-12f8f1b71421          2            30               10.573003           6                  6            5             26.596184                         9                     93                       93                  3.2                     8.8                4.8                      4.6              4.1   145.113442     11.407034        14.813044   11.593912         153.301345                7              False                  False        False            False                   True                      True                                  1                       45.0                        0                                0                   0         False     0.428897         20.730492           False
4  df159a97-3a78-4b08-a524-ec433c75b670          2            60               58.284620          12                  1            9             26.204152                        49                    141                      134                  7.5                     9.5                4.0                      3.9              4.6   100.000000     11.572232        13.716308   13.272883         111.128807                2               True                  False        False            False                  False                     False                                  6                       25.1                        0                                0                   7          True     0.441618         50.000000           False

In [8]:
# save the engineered dataset
df.to_csv('../data/processed/food_delivery_final.csv', index=False)